/*
 * This source file was generated by the Gradle 'init' task
 */
package concurrency;

import concurrency.phase1.Exercise1_1_SimpleThread;
import concurrency.phase1.Exercise1_2_MultipleThreads;
import concurrency.phase1.Exercise1_3_ThreadJoin;
import concurrency.phase1.Exercise1_4_RaceCondition;
import concurrency.phase1.Exercise1_5_ThreadInterrupt;
import concurrency.phase1.Exercise1_6_ThreadLifecycle;
import concurrency.phase2.Exercise2_1_SynchronizedCounter;
import concurrency.phase2.Exercise2_2_ThreadSafeBankAccount;
import concurrency.phase2.Exercise2_3_Deadlock;
import concurrency.phase2.Exercise2_4_Volatile;
import concurrency.phase2.Exercise2_5_ProducerConsumer;
import concurrency.phase3.Exercise3_1_ReentrantLock;
import concurrency.phase3.Exercise3_2_ReadWriteLock;
import concurrency.phase3.Exercise3_3_ConditionProducerConsumer;
import concurrency.phase3.Exercise3_4_StampedLock;
import concurrency.phase3.Exercise3_5_LockingPerformanceComparison;

public class App {
    public static void main(String[] args) {
        if (args.length == 0) {
            printMenu();
            return;
        }
        
        String exercise = args[0];
        switch (exercise) {
            case "1.1":
            case "1-1":
                System.out.println("Running Exercise 1.1: Simple Thread\n");
                Exercise1_1_SimpleThread.main(new String[0]);
                break;
            case "1.2":
            case "1-2":
                System.out.println("Running Exercise 1.2: Multiple Threads\n");
                Exercise1_2_MultipleThreads.main(new String[0]);
                break;
            case "1.3":
            case "1-3":
                System.out.println("Running Exercise 1.3: Thread Join\n");
                Exercise1_3_ThreadJoin.main(new String[0]);
                break;
            case "1.4":
            case "1-4":
                System.out.println("Running Exercise 1.4: Race Condition\n");
                Exercise1_4_RaceCondition.main(new String[0]);
                break;
            case "1.5":
            case "1-5":
                System.out.println("Running Exercise 1.5: Thread Interrupt\n");
                Exercise1_5_ThreadInterrupt.main(new String[0]);
                break;
            case "1.6":
            case "1-6":
                System.out.println("Running Exercise 1.6: Thread Lifecycle\n");
                Exercise1_6_ThreadLifecycle.main(new String[0]);
                break;
            case "2.1":
            case "2-1":
                System.out.println("Running Exercise 2.1: Synchronized Counter\n");
                Exercise2_1_SynchronizedCounter.main(new String[0]);
                break;
            case "2.2":
            case "2-2":
                System.out.println("Running Exercise 2.2: Thread-Safe Bank Account\n");
                Exercise2_2_ThreadSafeBankAccount.main(new String[0]);
                break;
            case "2.3":
            case "2-3":
                System.out.println("Running Exercise 2.3: Deadlock\n");
                Exercise2_3_Deadlock.main(new String[0]);
                break;
            case "2.4":
            case "2-4":
                System.out.println("Running Exercise 2.4: Volatile\n");
                Exercise2_4_Volatile.main(new String[0]);
                break;
            case "2.5":
            case "2-5":
                System.out.println("Running Exercise 2.5: Producer-Consumer\n");
                Exercise2_5_ProducerConsumer.main(new String[0]);
                break;
            case "3.1":
            case "3-1":
                System.out.println("Running Exercise 3.1: ReentrantLock\n");
                Exercise3_1_ReentrantLock.main(new String[0]);
                break;
            case "3.2":
            case "3-2":
                System.out.println("Running Exercise 3.2: ReadWriteLock\n");
                Exercise3_2_ReadWriteLock.main(new String[0]);
                break;
            case "3.3":
            case "3-3":
                System.out.println("Running Exercise 3.3: Condition Producer-Consumer\n");
                Exercise3_3_ConditionProducerConsumer.main(new String[0]);
                break;
            case "3.4":
            case "3-4":
                System.out.println("Running Exercise 3.4: StampedLock\n");
                Exercise3_4_StampedLock.main(new String[0]);
                break;
            case "3.5":
            case "3-5":
                System.out.println("Running Exercise 3.5: Locking Performance Comparison\n");
                Exercise3_5_LockingPerformanceComparison.main(new String[0]);
                break;
            default:
                System.out.println("Unknown exercise: " + exercise);
                printMenu();
        }
    }
    
    private static void printMenu() {
        System.out.println("=== Java Concurrency Study Plan ===");
        System.out.println("\nPhase 1: Thread Fundamentals");
        System.out.println("  1.1 - Simple Thread");
        System.out.println("  1.2 - Multiple Threads");
        System.out.println("  1.3 - Thread Join");
        System.out.println("  1.4 - Race Condition");
        System.out.println("  1.5 - Thread Interrupt");
        System.out.println("  1.6 - Thread Lifecycle");
        System.out.println("\nPhase 2: Synchronization Basics");
        System.out.println("  2.1 - Synchronized Counter");
        System.out.println("  2.2 - Thread-Safe Bank Account");
        System.out.println("  2.3 - Deadlock");
        System.out.println("  2.4 - Volatile");
        System.out.println("  2.5 - Producer-Consumer");
        System.out.println("\nPhase 3: Java Concurrency Utilities - Locks");
        System.out.println("  3.1 - ReentrantLock");
        System.out.println("  3.2 - ReadWriteLock");
        System.out.println("  3.3 - Condition Producer-Consumer");
        System.out.println("  3.4 - StampedLock");
        System.out.println("  3.5 - Locking Performance Comparison");
        System.out.println("\nUsage: ./gradlew run --args=\"1.1\"");
        System.out.println("Or: java -cp build/classes concurrency.App 1.1");
    }
}
