/*
 * This source file was generated by the Gradle 'init' task
 */
package concurrency;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appCanRun() {
        // Basic test to ensure App class can be instantiated
        // The main functionality is tested by running the exercises
        assertNotNull(App.class, "App class should exist");
    }
}
